config/routes.rb
Rails.application.routes.draw do

	# root 'static_pages#index'
	root 'posts#index'

	resources :attachments

	resources :posts
	resources :posts, path: :portfolio

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

	mount_uploader :attachment, S3Uploader
	belongs_to :parent, polymorphic: true

	def file(size=nil)
		self.attachment.url(size)
	end

end

app/models/post.rb
class Post < ActiveRecord::Base

	has_many :attachments, as: :parent, dependent: :destroy
	accepts_nested_attributes_for :attachments, allow_destroy: true, reject_if: proc { |attributes| attributes[:attachment].nil? }

	default_scope { includes(:attachments) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:parent_id, :parent_type)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
	 @post.attachments.build
  end

  # GET /posts/1/edit
  def edit
	  @post.attachments.build
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, attachments_attributes: [:id, :attachment, :_destroy])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/attachments/_attachment.html.erb
<div class="col-xs-6 col-sm-4 col-md-3">
	<div class="thumbnail">
		<div class="embed-responsive embed-responsive-16by9">
			<%= image_tag attachment.file(:thumb), class: 'img-responsive center-block' %>
		</div>
		<div class="caption small">
			Caption
		</div>
	</div>
</div>

app/views/attachments/_form.html.erb
<%= form_for(@attachment) do |f| %>
  <% if @attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
      <% @attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.text_field :parent_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

app/views/attachments/index.html.erb
<h1>Listing Attachments</h1>

<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.parent %></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', attachments_path %>

app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parent:</strong>
  <%= @attachment.parent %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<title>Heggaton</title>
	<%= stylesheet_link_tag    "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
	<![endif]-->

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

	<%= yield :head %>
</head>
<body>

	<%#= render 'layouts/nav' %>

	<div class="container">
		<%= yield %>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= nested_form_for @post, html: { multipart: true } do |f| %>

<% if @post.errors.any? %>
<div id="error_explanation">
	<strong><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</strong>
	<ul>
		<% @post.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="form-group form-group-lg">
	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>
</div>

<div id="nested-fields" class="row">
	<%= f.fields_for :attachments do |ff| %>
	<div class="col-xs-6 col-sm-4 col-md-3">
		<div class="thumbnail">
			<div class="embed-responsive embed-responsive-16by9">
				<% unless ff.object.persisted? %>

				<p class="lead text-center">
					Select a File
				</p>

				<div class="input-group input-group-md">
					<span class="input-group-btn">
						<span class="btn btn-info btn-file">
							Browse... <%= ff.file_field :attachment %>
						</span>
					</span>
					<input type="text" class="form-control" readonly>
				</div>

				<% else %>
				<%= image_tag ff.object.attachment.url(:thumb), class: 'img-responsive center-block' %>
				<% end %>
			</div>
			<p class="help-block">
				<% if ff.object.persisted? %>
				<%= ff.link_to_remove '<i class="fa fa-fw fa-remove"></i> Remove'.html_safe, data: {confirm: 'Are you sure?'} %>
				<% else %>
				<%= ff.link_to_remove '<i class="fa fa-fw fa-remove"></i> Remove'.html_safe %>
				<% end %>
			</p>
		</div>
	</div>
	<% end %>
</div>

<p class="text-right">
	<%= f.link_to_add '<i class="fa fa-fw fa-plus"></i> Add Attachment'.html_safe, :attachments, class: 'btn btn-default btn-sm', data: { target: '#nested-fields'} %>
</p>

<div class="form-group">
	<%= f.submit nil, class: 'btn btn-primary' %>
</div>

<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<header class="page-header">
	<%= link_to 'New Post', new_post_path, class: 'pull-right' %>
	<h2>
		Portfolio
	</h2>
</header>

<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-sm-7 col-md-8">

		<p class="lead">
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		</p>
		<p>
			Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		</p>

	</div>
	<div class="col-sm-5 col-md-4">
		<div class="table-responsive">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Job Name</th>
						<th colspan="2"></th>
					</tr>
				</thead>

				<tbody>
					<% @posts.each do |post| %>
					<tr>
						<td><%= link_to post.name, post %></td>
						<td><%= link_to 'Edit', edit_post_path(post) %></td>
						<td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<header class="page-header">
	<h2>
		<%= @post.name %>
	</h2>
</header>

<p id="notice"><%= notice %></p>

<div class="row">
	<%= render @post.attachments %>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>